name: Demo manual

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: "Mensaje a mostrar"
        required: true
        type: string

jobs:
  mostrar-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        env:
          MENSAJE: ${{ inputs.mensaje }}
        run: echo "$MENSAJE"
